version: '3.8'

services:
  postgres:
    image: postgres:16.4-alpine3.20
    container_name: postgres
    restart: always
    volumes:
      - db:/var/lib/postrgresql/data/
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
      POSTGRES_USER: postgres
volumes:
  db:
