version: '3.8'

services:
  postgres:
    image: postgres:16.4-alpine3.20
    container_name: postgres
    restart: always
    volumes:
      - db:/var/lib/postrgresql/data/
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
      POSTGRES_USER: postgres
  book_management_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-management-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      STAGE: production
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: books
    depends_on:
      - postgres
  
volumes:
  db:
